FROM node:24.8.0-bookworm-slim AS build
WORKDIR /app
RUN corepack enable
COPY package.json yarn.lock .yarnrc.yml ./
COPY .yarn ./.yarn
COPY apps ./apps
COPY packages ./packages
COPY tsconfig.base.json tsconfig.json ./
ARG API_INTERNAL_URL=http://api:3001
ENV API_INTERNAL_URL=$API_INTERNAL_URL
RUN yarn install --immutable && yarn workspace @tms/contracts build && yarn workspace @tms/web build

FROM node:24.8.0-bookworm-slim AS runtime
ENV NODE_ENV=production
WORKDIR /app
RUN corepack enable
COPY --from=build /app /app
USER node
EXPOSE 3000
CMD ["yarn", "start:web"]
